version: "3"

services:
  api-aec:
    image: registry.digitalocean.com/dcr-samuel/aec-brasil-api:${TAG}
    container_name: aec-brasil-api
    build: 
      context: Aec.Brasil
      dockerfile: ./Aec.Brasil.Api/Dockerfile
      args:
        - TAG=${TAG}
    ports:
      - "5020:5020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5020
      - ConnectionStrings__DefaultConnection="Server=aec-brasil-db,5022;Database=AecBrasil;User Id=sa;Password=YourStrong@Passw0rd;"
    depends_on:
      - db-aec
    command: bash -c "dotnet ef database update && dotnet Aec.Brasil.Api.dll"    
    networks:
      - rede-aec    

  db-aec:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: aec-brasil-db
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5022:1433"
      
networks:
  rede-aec:
    driver: bridge
  