name: CI_CD_PRD

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  REGISTRY: "registry.digitalocean.com/dcr-samuel"
  IMAGE_NAME_API: "aec-brasil-api"
  IMAGE_NAME_DB: "aec-brasil-db"

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout the repo 
        uses: actions/checkout@v2        
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      
      # #- name: Remove all old images from other repositories
      # #  run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME_API)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME_API) $(doctl registry repository list-tags $(echo $IMAGE_NAME_API) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Set TAG environment variable
        run: echo TAG=$(echo $GITHUB_SHA | head -c7) >> $GITHUB_ENV

      - name: Build Docker Image
        env:
          TAG: ${{ env.TAG }}
        run: |
          docker-compose -f docker-compose.yml build --no-cache --build-arg TAG=$TAG
          docker image ls

      - name: Push Docker Image
        run: docker-compose -f docker-compose.yml push
                  
            
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs:
            IMAGE_NAME_API, IMAGE_NAME_DB,
            REGISTRY, {{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}, GITHUB_SHA
          script: |
            # Login to registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            
            echo "Arquivos e diretórios no servidor remoto:"
            ls -al

            # Stop old containers
            #docker stop $(echo $IMAGE_NAME_API)
            #docker stop $(echo $IMAGE_NAME_DB)
            
            # Remove old containers
            #docker rm $(echo $IMAGE_NAME_API)
            #docker rm $(echo $IMAGE_NAME_DB)
            
            # Run new containers
            docker run -dt -p 5020:8080 \
            --restart always \
            --name $(echo $IMAGE_NAME_API) \
            --network $(echo $NETWORK_NAME) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME_API):$(echo $GITHUB_SHA | head -c7)
            
            docker run -dt -p 5022:1433 \
            --restart always \
            --name $(echo $IMAGE_NAME_DB) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME_DB):latest

